### ISSUE TITLE
FreeRTOS?

### ISSUE THREAD

**Issue by samuk** [theAgingApprentice/rosBot#5]
Hi is this a FreeRTOS project? It might be interesting for this: https://github.com/rosmo-robot/Rosmo_ROS2_Diffdrive

A bit of an overview of where we're at is here: https://github.com/rosmo-robot/Rosmo_ESC/issues/5 It would be great if you were interested in getting involved.

**Comment by theAgingApprentice** [comment]
A more accurate characterization is that this is the very early stages of a micoROS project in which FreeRTOS will play part. I am brand new to micoROS but I have been using Arduino on ESP32 for a few years now (it was rough going in the early days but this is a completely viable solution stack now). During that time I have played about with some of the FreeRTOS services. I have been eyeing ROS and ROS2 for a while but now that it has been ported to the ESP32 I figure it is worth a look. I am essentially looking to see if I can make a microROS drop-in replacement for the Arduino firmware that my buddy and I have written for our past robot projects. I checkout out your project and it sounds like you guys are sorting out your architecture at the moment as well. I will be sure to check in on you from time to time to see how you are progressing.  I will also be faithfully updating this repository with everything that I learn. I am not sure how far I will get with this but welcome you to leverage anything I do that yo find helpful. Good luck with your project!
